version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro            # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock.ro                        # Additional information
    user: root
    restart: on-failure
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: sfgbeerworks/sfg-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: sfgbeerworks/sfg-brewery-config
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://user:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  inventory-service:
    image: sfgbeerworks/sfg-brewery-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://user:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
  inventory-failover:
    image: sfgbeerworks/sfg-brewery-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
  beer-service:
    image: sfgbeerworks/sfg-brewery-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://user:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerservice
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
  order-service:
    image: sfgbeerworks/sfg-brewery-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://user:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/orderservice
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
  gateway:
    image: sfgbeerworks/sfg-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - beer-service
      - order-service
      - inventory-failover
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://user:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"